python main.py \
    --train_data_path="/export/sdb/shelldream/training_data_2016-04-01.txt" \
    --train_data_path="/export/sdb/shelldream/training_data_2016-04-02.txt" \
    --train_data_path="/export/sdb/shelldream/training_data_2016-04-03.txt" \
    --train_data_path="/export/sdb/shelldream/training_data_2016-04-04.txt" \
    --train_data_path="/export/sdb/shelldream/training_data_2016-04-05.txt" \
    --train_data_path="/export/sdb/shelldream/training_data_2016-04-06.txt" \
    --train_data_path="/export/sdb/shelldream/training_data_2016-04-07.txt" \
    --train_data_path="/export/sdb/shelldream/training_data_2016-04-08.txt" \
    --test_data_path="/export/sdb/shelldream/training_data_2016-04-09.txt" \
    --test_data_path="/export/sdb/shelldream/training_data_2016-04-10.txt" \
    --test_data_path="/export/sdb/shelldream/training_data_2016-04-11.txt" \
    --data_type="csv_with_schema" \
    --schema_file="fmap.schema.bak" \
    --model="xgboost" \
    --task="classification" \
    --model_path="./model/default_model.pickle.dat" \
    --parameter="{'n_estimators':100, 'max_depth':3, 'eta': 0.5, 'silent': 0, 'booster':'gbtree', 'objective': 'binary:logistic','eval_metric':'error','rate_drop':0.5, 'skip_rate':0.8, 'gamma': 0.1, 'max_delta_step':0, 'subsample':1, 'colsample_bytree':1, 'alpha':0, 'lambda':1, 'scale_pos_weight':1}" \
    --mode="analysis" 
    #--mode="train" 
